name: Deploy DotNet project to AWS EC2

on:
  push:
    branches: ["main"]

env:
  DOTNET_VERSION: ${{ secrets.DOTNET_VERSION }}  # Use secret for .NET version

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ secrets.DOTNET_VERSION }}

    - name: 'Publish Project Using Dotnet'
      run: |
        pushd './'
        dotnet publish --configuration Release --output ./output --self-contained
        popd

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key
        chmod 600 private_key

    - name: 'Deploy to EC2'
      run: |
        scp -i private_key -o StrictHostKeyChecking=no -r ./output ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/myapp
        ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo systemctl restart myapp.service
        EOF