name: Deploy DotNet project to AWS EC2

on:
  push:
    branches: ["main"]

env:
  DOTNET_VERSION: 9.0.x                  # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Publish Project Using Dotnet'
      run: |
          pushd './'
          dotnet publish --configuration Release --output ./output --self-contained
          popd

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key
        chmod 600 private_key

        - name: Copy files to EC2
        run: |
          scp -i private_key -o StrictHostKeyChecking=no -r ./output ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/myapp
  
    - name: Run commands on EC2
      run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo systemctl restart myapp.service
          EOF